language: php

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR=.phpunit

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION="2.7.*"
    - php: 7.1
      env: SYMFONY_VERSION="2.8.*"
    - php: 7.1
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.1
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.1
      env: SYMFONY_VERSION="4.1.*"
    # Test latest PHP against all symfony versions
    - php: 7.2
      env: SYMFONY_VERSION="2.7.*"
    - php: 7.2
      env: SYMFONY_VERSION="2.8.*"
    - php: 7.2
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.1.*"

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/framework-bundle:"${SYMFONY_VERSION}"; fi
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/console:"${SYMFONY_VERSION}"; fi

install:
    - composer update $COMPOSER_FLAGS

script: bin/phpunit -v
